---

- name: Assert that master_token is specified
  fail: msg="License key must be supplied for BWC enterprise installation."
  when: bwc_license is not defined

- name: Create packagecloud dir
  become: yes
  file:
    path: "/etc/packagecloud"
    mode: "u=rwx,g=rx,o=rx"
    owner: st2
    group: st2
    state: directory

- name: Get read token for repo from packagecloud
  become: yes
  no_log: yes
  uri:
    url: https://{{ bwc_license }}:@packagecloud.io/install/repositories/StackStorm/{{ bwc_pkg_repo }}/tokens.text
    creates: "/etc/packagecloud/StackStorm_{{ bwc_pkg_repo }}_read_token.txt"  # Don't download if file already exists
    dest: "/etc/packagecloud/StackStorm_{{ bwc_pkg_repo }}_read_token.txt"
    force_basic_auth: yes
    method: POST
    status_code: 201,200
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body: "name={{ ansible_nodename }}"

- name: Set bwc_read_token variable
  become: yes
  no_log: yes
  set_fact:
    bwc_read_token: "{{ lookup('file', '/etc/packagecloud/StackStorm_{{ bwc_pkg_repo }}_read_token.txt') }}"

- name: Add BWC enterprise repos on {{ ansible_distribution }}
  include: bwc_repos_{{ ansible_pkg_mgr }}.yml
  tags:
    - BWC repos
    - StackStorm enterprise
  register: bwc_repo_added
  when: bwc_read_token != ''
