---

- name: Setup st2.conf auth backend to LDAP
  become: yes
  ini_file:
    dest: /etc/st2/st2.conf
    section: auth
    option: backend
    value: ldap
    backup: yes
  # Don't even setup LDAP if backend_kwargs is not defined
  with_dict: "{{ bwc_ldap.backend_kwargs | default({}) }}"
  notify:
    - restart st2api
    - restart st2stream

- name: Setup st2.conf auth backend_kwargs for LDAP
  become: yes
  ini_file:
    dest: /etc/st2/st2.conf
    section: auth
    option: backend_kwargs
    value: "{{ bwc_ldap.backend_kwargs | to_json | string }}"
    backup: yes
  with_dict: "{{ bwc_ldap.backend_kwargs | default({}) }}"
  notify:
    - restart st2api
    - restart st2stream
