---

- name: Setup st2.conf auth backend to LDAP
  become: yes
  ini_file:
    dest: /etc/st2/st2.conf
    section: auth
    option: backend
    value: ldap
    backup: yes
  notify:
    - restart st2api
    - restart st2stream

- name: Setup st2.conf auth backend_kwargs for LDAP
  become: yes
  ini_file:
    dest: /etc/st2/st2.conf
    section: auth
    option: backend_kwargs
    value: "{{ bwc_ldap.config | to_nice_json }}"
    backup: yes
  notify:
    - restart st2api
    - restart st2stream
