---

- name: Install latest bwc-enterprise package
  become: yes
  package:
    name: bwc-enterprise
    state: latest
  when: bwc_version == "latest"
  tags:
    - bwc
    - st2 enterprise

- name: Install pinned bwc-enterprise package
  become: yes
  package:
    name: bwc-enterprise={{ bwc_version }}-{{ bwc_revision }}
    state: present
  when: bwc_version != "latest"
  tags:
    - bwc
    - st2 enterprise

- name: Setup RBAC and setup roles and assignments if enable_rbac is defined
  include: "rbac.yml"
  when: rbac is defined

- name: Setup LDAP and set up LDAP configuration
  include: "ldap.yml"
  when: ldap is defined
