---

  - name: Create BWC RBAC directories
    become: yes
    file:
      path: "{{ item }}"
      mode: "u=rwx,g=r,o=r"
      owner: st2
      group: st2
      state: directory
    with_items:
      - /opt/stackstorm/rbac/assignments
      - /opt/stackstorm/rbac/roles

  - name: Copy RBAC roles to /opt/stackstorm/rbac/roles directory
    become: yes
    template:
      src: rbac_roles/roles.yml.j2
      dest: /opt/stackstorm/rbac/roles/{{ item.name }}.yaml
      owner: st2
      group: st2
    with_items: "{{ rbac.roles }}"
    when: bwc_rbac_roles is defined

  - name: Copy RBAC assignments to /opt/stackstorm/rbac/assignments directory
    become: yes
    template:
      src: rbac_assignments/assignments.yml.j2
      dest: /opt/stackstorm/rbac/assignments/{{ item.name }}.yaml
      owner: st2
      group: st2
    with_items: "{{ rbac.assignments }}"
    when: bwc_rbac_assignments is defined

  - name: Enable RBAC in st2 configuration
    become: yes
    ini_file:
      dest: /etc/st2/st2.conf
      section: rbac
      option: enable
      value: True
      backup: yes
    notify:
      - restart st2
      - reload bwc_rbac
      - restart st2api

